CREATE SCHEMA IF NOT EXISTS RELINK;

CREATE TABLE IF NOT EXISTS RELINK.SHORT_LINKS
(
    ID              BIGSERIAL PRIMARY KEY,
    CREATED_AT      TIMESTAMP    NOT NULL,
    DESTINATION_URL VARCHAR(2048),
    HASH            VARCHAR(256) NOT NULL UNIQUE
);
